### ISSUE TITLE
Unusable without immutable.js

### ISSUE THREAD

**Issue by wbuchwalter** [neilff/redux-ui-router#16]
Hey!
Redux-ui-router is currently pretty much unusable without immutable.js, since querying state.reducer returns an immutable.js data structure.

Since the reducer is very small, it would be quite trivial to implement immutability by convention with _.assign and such, and thus be able to use redux-ui-router without immutable.js.
What do you think?

**Comment by neilff** [comment]
It is my intention to do this, I'll try to get this done soon, if you want to submit a PR, feel free

**Comment by wbuchwalter** [comment]
Related PR: #18

**Comment by neilff** [comment]
The PR looks good, I'll take a look at it tomorrow morning and will likely merge it in shortly after, thanks

**Comment by wbuchwalter** [comment]
:+1:

**Comment by dmachat** [comment]
I'm having what appears to be a timing issue between `0.3.3` and `0.4.0` ie the changes described in this thread and #18. On `0.3.3`, router actions and state were behaving properly. After upgrading, there are two issues:

* `action @@reduxUiRouter/$stateChangeStart` get fired twice for ui-router actions.
* The `router` params seem to be a step behind eg on initial load `router.currentParams` is an empty object. On the ui-router action, `currentParams` gets populated, but by the state that applies to the initial load. The rest of the params are similarly one tick behind.

I tried for a while to figure out if I was doing something wrong, but I couldn't find anything. I can try to put together a plnkr or something if you need it.

**Comment by neilff** [comment]
@dmachat sure, a plunkr would be helpful, the issue you are describing sounds like what we attempted to resolve in #17

**Comment by dmachat** [comment]
@neilff sorry, it must be in my app. I created a simpler one to try to isolate, but couldn't recreate the issue. I'll follow up if I do find anything, and also planning to clean up and push the simple version as another example for redux-ui-router. thanks for the lib!

**Comment by neilff** [comment]
@dmachat no problem, thanks
