### ISSUE TITLE
State is not correctly set on application startup

### ISSUE THREAD

**Issue by mlegenhausen** [neilff/redux-ui-router#21]
When starting the app in a certain start and press refresh, then the router store does not get correctly initialized. It seems that `$locationChangeSuccess` fires before the `$state` object is set correctly. It always get initialized in the root state which is not correct.

I will try to get the error reproduced with your example.

**Comment by mlegenhausen** [comment]
Ok it is also in your example (if you can get it running cause of all the missing dependencies). Simply go to `http://localhost:3000` and look at the `currentState` everything is fine. Then refresh the page. You land in the root state instead of the app state.

**Comment by neilff** [comment]
@mlegenhausen https://github.com/neilff/redux-ui-router/issues/17 is dealing with a similar issue, but looks like there are issues with the initial state. I'll try to take a look into alternative methods of grabbing the initial state. `$urlRouter.sync`doesn't seem to be working.

**Comment by neilff** [comment]
@mlegenhausen I've updated `master` with a fix for this issue, I'll push a build later today with the fix onto NPM

**Comment by mlegenhausen** [comment]
Thanks :)

**Comment by neilff** [comment]
Fix is now published on npm [v0.4.1](https://www.npmjs.com/package/redux-ui-router)

**Comment by mlegenhausen** [comment]
Your release is broken. The whole `lib` folder is missing.

**Comment by neilff** [comment]
@mlegenhausen should be fixed now under `0.4.2` sorry about that

**Comment by neilff** [comment]
Should be OK in `0.4.2`

**Comment by mlegenhausen** [comment]
Thanks again ;)
