### ISSUE TITLE
Typescript definitions?

### ISSUE THREAD

**Issue by sstorie** [neilff/redux-ui-router#24]
Has anyone worked on creating a typescript definition file for redux-ui-router? I'm new to writing them, but was gonna try creating one, but if there's something already out there I'd like to use that.

**Comment by neilff** [comment]
There isn't one, and I don't have plans to make one at the moment, however if you want to make one, I am accepting PRs

**Comment by sstorie** [comment]
Ok, I'm still learning how to write them for external libraries, but I'll take a shot at it and submit a PR. Thanks!

**Comment by sstorie** [comment]
I just submitted a PR for the definition file. Thanks for the opportunity to contribute, and if you see any glaring issues please let me know and I'll work to clean them up.
