### ISSUE TITLE
Interaction with ui-sref directive

### ISSUE THREAD

**Issue by SyedSRahman** [neilff/redux-ui-router#27]
ui-router provides a ui-sref directive to directly trigger a state from inside angular partials. Should I stop using that to transition between states when I use redux-ui-router?

**Comment by neilff** [comment]
`ui-sref` can still be used, or you can build actions which trigger `STATE_GO` actions. The problem with *not* using `ui-sref` is that you will break browser behaviour (such as right click to open in new tab). You could also build a custom directive that would fire the proper action, but still act as an `<a>` tag as the browser expects.

**Comment by SyedSRahman** [comment]
Thanks @neilff, that was helpful.
