### ISSUE TITLE
redux-ui-router ignores $urlRouterProvider#deferIntercept behaviour

### ISSUE THREAD

**Issue by vdanchenkov** [neilff/redux-ui-router#31]
UI router have a feature to defer url change listening via $urlRouterProvider#deferIntercept. I use it to setup some $stateChangeStart callbacks before first state transition is fired. 

But redux-ui-router forces $urlRouter.sync on every $locationStateChange which triggers state change too early - before I call $urlRouter.listen();

As a workaround I call $rootScope.$on('$locationChangeStart', (evt) => evt.preventDefault()) before redux-ui-router took chance to subscribe and remove subscription when everything is ready.

**Comment by neilff** [comment]
Can you provide some code, we might be able to drop the `$urlRouter. sync()`. I haven't used what you mention here before, so I'd like to see some code if possible.

Or even a PR I could test would be nice. :+1:

**Comment by vdanchenkov** [comment]
@neilff I've edited example to highlight the problem. State4 is prohibited by some reason. In my case state availability is based on authorization check. If you try example app without suggested changes to RouterListener, app will not catch state change when it is opened by direct link http://localhost:3000/#/app/child4

**Comment by neilff** [comment]
I looked at the changes, however it breaks `reloadOnSearch` functionality. 

I have been using `reloadOnSearch` to push state to the router without having the application reload the controller that corresponds to that state. 

An example usage would be, I have a graph, and as I click on the graph, maybe it makes a new query, I want to push that query state to the route (for bookmarking), but I don't want the controller to be reloaded, this prevents that from happening. If a solution can be found to fix both of these issues, I can patch the project. 

I believe that UI router is attempting to fix this issue in the 1.0 release, however it is still in alpha.

**Comment by neilff** [comment]
Can you try this branch and see if it resolves the issues you are having? I've removed the url sync from the router listener. #31

**Comment by silver2k** [comment]
I see a few people have had issues with this - but no one (except me) has tested the new branch. What is the plan for releasing the patch?

**Comment by neilff** [comment]
I'll release it sometime this week when I get some free time

**Comment by silver2k** [comment]
Awesome, thanks for all your hard work Neil! :-)

**Comment by neilff** [comment]
#33 fixes this
