### ISSUE TITLE
Router current state seems a step behind on browser back/forward

### ISSUE THREAD

**Issue by silver2k** [neilff/redux-ui-router#32]
Hi,

Not sure what's going on - but I'm seeing weird behaviour when using the browser back/forward buttons. ui-router seems to work fine, but the actions from redux-ui-router seem to be a state behind.

> action @@reduxUiRouter/$stateChangeStart @ 00:53:18.881
> $stateChangeStart to undefined- fired when the transition begins. toState,toParams : 
>  Object {url: "/complete", views: Object, name: "app.complete"} Object {}
>   action @@reduxUiRouter/$stateChangeStart @ 00:53:18.895
> $stateChangeStart to undefined- fired when the transition begins. toState,toParams : 
>  Object {url: "/complete", views: Object, name: "app.complete"} Object {}
>  I think the current state is app.details
>   action @@reduxUiRouter/$stateChangeSuccess @ 00:53:18.905
> $stateChangeSuccess to app.complete- fired once the state transition is complete.
> $viewContentLoaded - fired after dom rendered Object {name: "$viewContentLoaded", targetScope: ChildScope, defaultPrevented: false, currentScope: Scope}currentScope: nulldefaultPrevented: falsename: "$viewContentLoaded"preventDefault: ()stopPropagation: ()targetScope: ChildScope__proto__: Object

Sorry the log is so hard to read - but the crux is, I created a reducer to watch for `@@reduxUiRouter/$stateChangeSuccess` and log the "I think the current state is:" `action.payload.currentState.name` - and the clicked forward in my browser to navigate from `app.details` to `app.complete`.

To me it looks like `@@reduxUiRouter/$stateChangeSuccess` fires before ui-router has actually changed state. The line `$stateChangeSuccess to app.complete- fired once the state transition is complete.` is from ui-router.
It's also firing `@@reduxUiRouter/$stateChangeStar` twice...

Any ideas?

**Comment by silver2k** [comment]
Nevermind - suggested fix in https://github.com/neilff/redux-ui-router/issues/31 fixes the issue.
Be great if you could pull it in though.

**Comment by neilff** [comment]
Can you check out this branch and inform me if this fixes your specific issue:
https://github.com/neilff/redux-ui-router/tree/remove-url-sync

The problem with the proposed fix is that it breaks `reloadOnSearch` functionality, but I believe this fix will resolve both issues.

**Comment by silver2k** [comment]
I don't use `reloadOnSearch` in my app at the moment, but I mocked something up to include that as well and it all appears to work correctly. It also seems to be faster - but maybe that's just me.

**Comment by neilff** [comment]
It's possible that the url sync code was expensive. Thanks, I'll merge this fix in if I get confirmation from the original issue , #31

**Comment by silver2k** [comment]
Embarrassingly - I'm still seeing this issue in the latest version :-( So much for my testing!
The current state of `@@reduxUiRouter/$stateChangeSuccess` still shows the previous state if you navigate by browser forward/back buttons, because the state change is triggered before ui-router applies it.

Changing:
'  $rootScope.$on('$locationChangeSuccess', function () {
    ngUiStateChangeActions.onStateChangeSuccess();
  });'
to
`  $rootScope.$on('$stateChangeSuccess', function () {
    ngUiStateChangeActions.onStateChangeSuccess();
  });`
 
Fixes it - does this affect reloadOnSearch?

**Comment by mrichard** [comment]
I seem to be noticing this as well. When using the browser back button, the router state is one step behind.

**Comment by silver2k** [comment]
If someone can try removing`$rootScope.$on('$locationChangeSuccess', function () { ngUiStateChangeActions.onStateChangeSuccess(); });` and test everything still works then that might help confirm things. I'm currently using a patched version - and it seems to be working fine, but our use case is pretty limited.

**Comment by mrichard** [comment]
Quickly tested and this seems to work: 

```JavaScript
 $rootScope.$on('$stateChangeSuccess', function () { ngUiStateChangeActions.onStateChangeSuccess(); });
```

Thank you! Is this enough a fix to make it in to master?

The only small issue I see is the order of events is switched when using the back/forward keys. stateGo comes after $stateChangeSuccess

**Comment by neilff** [comment]
Does the initial state of the router get published to the store on application startup (e.g. a hard refresh when on a route?)

**Comment by silver2k** [comment]
As in does `@@init` contain a populated `router.currentState`? Not for me it doesn't.

**Comment by neilff** [comment]
that is the issue with using `$stateChangeSuccess` instead of `$locationChangeSuccess` initially, `$locationChangeSuccess` will pick up the initial state of the application, the $stateChangeSuccess will not

**Comment by hally9k** [comment]
This seems to be fixed by https://github.com/neilff/redux-ui-router/pull/68
