### ISSUE TITLE
Pass the event of ui-router in the payloads

### ISSUE THREAD

**Issue by skimi** [neilff/redux-ui-router#34]
I think it would be useful to pass the event of ui-router in the payloads as to allow `e.preventDefault()`
https://github.com/angular-ui/ui-router/wiki#user-content-state-change-events

It has no place in the store but it can be used by middlewares to stop the transition and check some things and then redirect.

```
store => next => action => {
  if( action.type === STATE_CHANGE_START && hasNoAccess() ) {
    action.payload.evt.preventDefault()
    return next(stateGo('login'})
  }
  return next(action)
}
```

**Comment by neilff** [comment]
I can add it in the next update, or if you want to make a PR I can merge it in.

**Comment by neilff** [comment]
Will be available in next version

**Comment by neilff** [comment]
https://github.com/neilff/redux-ui-router/releases/tag/v0.5.1
