### ISSUE TITLE
Actions are repeated twice during the startup

### ISSUE THREAD

**Issue by AOlefirenko** [neilff/redux-ui-router#35]
Hi! I use angular 1.4.8 and ui-router 0.2.15 and just noticed that both events *@@reduxUiRouter/$stateChangeStart* and *@@reduxUiRouter/$stateChangeSuccess* are repeated twice with the equal payload during startup. It's critical for me coz I use *onEnter* hook to make http request for checking my access token.  
When I comment this event handler the target state is loaded only once and it seems all things are fine.
```javascript
$rootScope.$on('$locationChangeSuccess', function (evt) {
    evt.preventDefault();
    $urlRouter.sync();
    ngUiStateChangeActions.onStateChangeSuccess();
  });
```

Could you please clarify what the reason to use this code? May it be needed for older versions of ui-router?

**Comment by neilff** [comment]
There is a similar issue currently open, try the PR that is open to resolve that issue, and see if it will resolve the issue you are having: https://github.com/neilff/redux-ui-router/tree/remove-url-sync

**Comment by neilff** [comment]
#33 resolves this issue
