### ISSUE TITLE
loosen dependencies?

### ISSUE THREAD

**Issue by laurelnaiad** [neilff/redux-ui-router#37]
Hi, thanks for making this!

I just installed it via jspm and my installed forks exploded. :(

This is because of the very strict devDependencies in package.json. Could you be convinced to add `^` to the dependencies? it would make the module play more nicely with module resolution strategies such as jspm or even modern npm.

Cheers!

**Comment by neilff** [comment]
dependencies in `0.5.0` will be:

```
  "dependencies": {
    "redux": "^3.0.0"
  },
  "peerDependencies": {
    "angular": "^1.4.x",
    "angular-ui-router": "^0.2.15"
  }
```

**Comment by neilff** [comment]
Fixed in latest release: https://github.com/neilff/redux-ui-router/releases/tag/v0.5.1
