### ISSUE TITLE
onStateChangeSuccess not returning payload

### ISSUE THREAD

**Issue by Elijen** [neilff/redux-ui-router#40]
onStateChangeSuccess is not returning `payload` the same way as other action creators. This is causing  reducer to return `undefined` and producing the following Redux error:

`Error: Reducer "router" returned undefined handling "@@reduxUiRouter/$stateChangeSuccess". To ignore an action, you must explicitly return the previous state.`

**Comment by Elijen** [comment]
Seems to be fixed here: https://github.com/neilff/redux-ui-router/blob/c762b1186a445e54a0d38a6cea194774ba947a81/src/router-state-reducer.js

Will leave the issue open until somebody more familiar with the code confirms.

**Comment by neilff** [comment]
The latest publish will contain the above fix, feel free to re-open if the issue arises again, thanks
