### ISSUE TITLE
stateGo() doesn't update currentParams

### ISSUE THREAD

**Issue by danielwalczak** [neilff/redux-ui-router#48]
I found this issue, when i wanted to change query params in current state.
This action doesn't update params via reducer, because '$stateChangeSuccess' is not trigger. 

e.g
Current state is 'Home' and then do stateGo('Home', { filter: 'test' }).

**Comment by JesterXL** [comment]
I'm having the same problem. In my old code, it'd be something like [here](https://github.com/angular-ui/ui-router/issues/1758#issuecomment-230806749) where I use the `$state.go`'s promise to access the `$stateParams` after the the then. Here, however, I don't really have a then to access using Redux, and a bunch of logs confirm they never update anyway.

Will report back if I find a hackaround.

**Comment by JesterXL** [comment]
If I comment out the `unsubcribeStateChangeListener` method on line #19 of `router-listener.js`, the `$locationChange` event continues to fire and appears to correctly update the store now. Not sure of adverse effects yet.

**Comment by hally9k** [comment]
@JesterXL @danielwalczak  I think this is fixed in the new version (0.6.0). At least I cant reproduce it in the example on my end. If you want to have a jam and see if it's working for your cases that would be awesome.
