### ISSUE TITLE
How to use angular-ui-router resolve with redux-ui-router

### ISSUE THREAD

**Issue by lordnox** [neilff/redux-ui-router#50]
I'm currently trying to figure out how to integrate ui-routers resolve mechanic into the redux-state.

```
$stateProvider.state('app', {
  url : "/", 
  abstract : true,
  resolve : {
    state: $ngRedux => $ngRedux.getState()
  }
})
```

The code above will give me the current state in my app, but will never be re-evaluated. Which makes redux quite useless for using it with ui-router.

I'd like to use the resolve syntax in concert with the component syntax like this:
```
$stateProvider.state('app.dashboard', {
  url : "/dashboard",
  component: "DashboardContainer",
  resolve : {
    Auth: state => state.Auth, // fetches the Auth-state from the redux-store
    isAdmin : Auth => Auth.isAdmin
  }
})
```

I actually did not expect this to work, at least not from what I've read in the source. 
But I'd love to have this kind of syntax. 

How are you using the states resolve methods?
Do you abandon this in favor of `$scope.$on("destroy", $ngRedux.connect ... `in every controller?

Thanks

**Comment by alejandroSuch** [comment]
Have the same question. How did you finally manage this? I'm resolving some data on my controller's constructor, but I need some other elements to be resolved before to decide a redirection

**Comment by lordnox** [comment]
I'm still working on it...
```
$stateProvider.state('app.dashboard', {
  url : "/dashboard",
  component: "DashboardContainer",
  resolve : {
    mapStateToProps : function(myService) { return state => { 
      Auth: state => state.Auth, // fetches the Auth-state from the redux-store
      isAdmin : Auth => Auth.isAdmin
    } 
    mapDispatchToProps : function(AuthActions) { return dispatch => {
      logout : () => dispatch(AuthActions.logout())
    }
  },
  controller : "defaultReduxController"
})

.controller("defaultReduxController", function ($scope, $ngRedux, mapStateToProps, mapDispatchToProps) {
  $scope.$on("$destroy", $ngRedux.connect(mapStateToProps, mapDispatchToProps)(this))
  return this
});
```

I let ui router create the 2 functions, mapState and mapDispatch. This will be mapped on a state to state basis to a controller, usually you'll only need the default controller.

**Comment by hally9k** [comment]
There is an example of how I am using resolves with redux-ui-router in an answer to [this issue here](https://github.com/neilff/redux-ui-router/issues/47). I am currently working on a clearer example app which will include an example of a thunk returning a promise to a state resolve like this.
