### ISSUE TITLE
How to use $stateParams in resolve from state ui-router configuration ?

### ISSUE THREAD

**Issue by michalpanek** [neilff/redux-ui-router#65]
I have state configuration like that: 

```javascript
params: {
          bindingsObj: -1
        },
        resolve: {
          bindingsObj: ($stateParams) => $stateParams.bindingsObj
        }
```

and what can I use that configuration, resolve $stateParams etc. when I use **stateGo** with redux-ui-router ?

When I use **_stateGo_** like above then I get error:

> angular.js:13920TypeError: Cannot convert undefined or null to object
    at routerStateReducer (router-state-reducer.js:32)
    at combination (combineReducers.js:117)
    at dispatch (createStore.js:179)

------------
what this info is not exist in redux-ui-router doc, or examples ?

**Comment by hally9k** [comment]
[This issue](https://github.com/neilff/redux-ui-router/issues/50) is in the same vein... Resolves are not supported yet as far as I know.
