### ISSUE TITLE
Losing state params when refreshing the page

### ISSUE THREAD

**Issue by Nighthawk14** [neilff/redux-ui-router#66]
Hi,

Testing the new ui-router 1.0.0-beta.1 compatibility #61, it occurs that when you refresh a page the state params are not propagated to the state in the store (e.g `/foo/1` where `/1` is `/:id` will results in `/foo/undefined` after refreshing the page and is not part of the properties `fromParams` and `toParams` of the `onStart` and `onSuccess` actions).

Trying to find out if it's an issue with ui-router or with redux-ui-router right now.

ps: I tried with and without html5location enabled
ps2: I tried serving the files via webpack-dev-server or via nginx, same result.

**Comment by Nighthawk14** [comment]
After a bit of investigation, it appears that the param is actually propagated to the state in the store but later than before. So let's say your state has a controller, you expect the param to be already present at instantiation of your controller. With the current redux-ui-router and ui-router this happens. When with the new redux-ui-router and ui-router1.0.0-beta.1 the param is populated to the store later on so not available in the constructor of your controller.

**Comment by hally9k** [comment]
If you want to submit a PR I can merge it in ASAP. Otherwise, with your awesome direction here, I should be able to patch this a bit later today.

**Comment by Nighthawk14** [comment]
Haha no worries, I checked a bit further but then I had a meeting... I want to create a plunker first with ui-router to make sure we can make it. I can actually see in the `treeChanges` the param populated in the `onStart` hook, but I don't see what is wrong with using `to().params` in this hook, that seems to be the right thing to do :).

**Comment by Nighthawk14** [comment]
Hey @hally9k, I'm testing with the new version this morning and it appears that the issue is still there. It's definitely better because now we have the right params in the `toParams` property of the `onStart` action so that's cool. The problem is that we update the store only on `onSuccess` but this action occurs after the instantiation of the state and it's controller, so we still don't have the params at this time. The thing to do would be to update the state at `onStart`, and then re-update it at `onSuccess` or leave like like that, or clean it at `onError`. What do you think about that?
