### ISSUE TITLE
UI-Router $resolve

### ISSUE THREAD

**Issue by sfthomas** [neilff/redux-ui-router#71]
I tried to find any resources on how to access the resolved data for ui-router states in a redux-way.
It is still possible to get hold of those by injecting into the controller/binding to a component, but the best would be if they were available in the redux store. 
Is there any way to do/support this?

**Comment by hally9k** [comment]
I'm not entirely sure I understand your issue. Would you mind expanding on your explanation a little bit? There is an example on [this issue](https://github.com/neilff/redux-ui-router/issues/47) that addresses resolves. Is this helpful?

**Comment by sfthomas** [comment]
Yes, I think it helps - I shall try to adjust my code according to that example.
Apologies for not finding that myself.

**Comment by hally9k** [comment]
No worries ;)
