### ISSUE TITLE
Getting ` Cannot convert undefined or null to object` when adding router to combineReducers

### ISSUE THREAD

**Issue by xlozinguez** [neilff/redux-ui-router#72]
Hey there,

I'm getting the following when adding the router to my redux store:

```
angular.js?3437:13920TypeError: Cannot convert undefined or null to object
    at routerStateReducer (eval at <anonymous> (bundle.js?80e2857…:3158), <anonymous>:32:16)
    at combination (eval at <anonymous> (bundle.js?80e2857…:3002), <anonymous>:132:29)
    at i (<anonymous>:1:14096)
    at u (<anonymous>:1:14382)
    at <anonymous>:1:17277
    at Object.dispatch (eval at <anonymous> (bundle.js?80e2857…:2948), <anonymous>:179:22)
    at dispatch (<anonymous>:1:17719)
    at eval (eval at <anonymous> (bundle.js?80e2857…:3134), <anonymous>:9:31)
    at eval (eval at <anonymous> (bundle.js?80e2857…:5361), <anonymous>:89:29)
    at eval (eval at <anonymous> (bundle.js?80e2857…:5409), <anonymous>:62:22)
```

For some context, it was working fine and then I hooked up [redux-observables](https://github.com/redux-observable/redux-observable) which leverages its own [middleware](https://github.com/redux-observable/redux-observable/blob/master/docs/basics/SettingUpTheMiddleware.md)

Note that the router params is correctly added to the store but the state is not correctly handled (no data seems to be stored).

You can test in the context of [my demo app](https://github.com/axialmarket/axial-stockObservr/).

**Comment by xlozinguez** [comment]
Update: Not sure if that's the prettiest way but I ended up creating an epic around the `@@reduxUiRouter/$stateChangeStart` action to handle fetching the page resources: [this way](https://github.com/axialmarket/axial-stockObservr/blob/master/client/src/common/epics/routes.epics.js) ... 

Unfortunately, since the `$stateChangeSuccess`action doesn't provide the corresponding state params, I had to use the $stateChangeStart... If someone had to deal with the same sort of thing, I'm all hear :)

**Comment by hdjirdeh** [comment]
Was seeing the same issue but then realized that I forgot to include `thunk` and the appropriate middleware when creating the store, that solved the problem :)

    $ngReduxProvider.createStoreWith(
        reducer,
        ['ngUiRouterMiddleware', thunk, Logger]
      );

**Comment by hally9k** [comment]
@xlozinguez did adding the thunk middleware fix this for you aswell?

**Comment by hally9k** [comment]
@xlozinguez - closing but feel free to reopen if you still have this issue.
