### ISSUE TITLE
The engine "node" is incompatible with this module.

### ISSUE THREAD

**Issue by zalishchuk** [neilff/redux-ui-router#84]
Can you please publish the latest version to npm? The current latest on npm is 0.6.0, the Github one is 0.6.1.

My Node version is v7.2.1.

```
error redux-ui-router@0.6.0: The engine "node" is incompatible with this module. Expected version "6.3.0".
error Found incompatible module
```

**Comment by graingert** [comment]
@hally9k @neilff can we get a new npm release?

**Comment by graingert** [comment]
we could all move to https://www.npmjs.com/package/hally9k-redux-ui-router

**Comment by McAllaster** [comment]
This has been a problem for over a month. Could we get an updated release, it should be fixed on the master branch as per [this commit](https://github.com/neilff/redux-ui-router/commit/ba8d270a97a39d409bc11495e56177ebf7e61bae).

**Comment by zalishchuk** [comment]
@McAllaster I think this project is abandoned by its contributors

**Comment by kunyan** [comment]
@neilff @hally9k  Please at least release 0.6.1 to fix the node engine check

**Comment by hally9k** [comment]
Hello all,

I have been swamped with a new position I started this year. I will get
this repo up to speed and push new packages tomorrow morning. Apologies and
thanks for everyone's patience.
Hal

**Comment by hally9k** [comment]
0.6.1 release fixes this now.

**Comment by graingert** [comment]
Neato
